title: Laura Bunel # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  As an aspiring data analyst, I bring a diverse background and a strong foundation in customer service and sales roles. With my previous customer-focused role I honed my communication skills which have allowed me to exceed performance targets, but also showcased my attention to detail. Adding to my experience, completing a data analysis bootcamp has taught me the necessary skills to work in the data world. I am enthusiastic about translating my varied skill set into a dynamic career in data analysis, leveraging my past experiences to uncover insights and drive informed decisions. 
  <br><br>
  <a href="https://www.linkedin.com/in/laura-bunel/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
